services:
  - type: web
    name: votavision-backend
    runtime: docker
    plan: free
    region: frankfurt
    branch: deployconfirmed
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_BASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: 587
      - key: JWT_DURATION_SECONDS
        value: 3600
      - key: SPRING_JPA_SHOW_SQL
        value: false
